### ISSUE TITLE
Convert .gctx file to .gct

### ISSUE THREAD

**Issue by FarshidShekari** [cmap/cmapPy#47]
this is my code for that purpose:
```
import sys
from cmapPy.pandasGEXpress import gctx2gct


def main():
    gctx2gct.gctx2gct_main(sys.argv)


if __name__ == '__main__':
    main()
```
and when I want to run it from consol I get below error:

```
Traceback (most recent call last):
  File "gct2npy.py", line 25, in <module>
    main()
  File "gct2npy.py", line 8, in main
    gctx2gct.gctx2gct_main(sys.argv)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-package
s\cmapPy\pandasGEXpress\gctx2gct.py", line 51, in gctx2gct_main
    in_gctoo = parse_gctx.parse(args.filename, convert_neg_666=False)
AttributeError: 'list' object has no attribute 'filename'
```

indeed I want to write equal code for below code(is in `deprecate `version of `cmap`) in `cmappy`:
```
import sys
import numpy as np
import cmap.io.gct as gct


def main():
    infile = sys.argv[1]
    outfile = sys.argv[2]
    
    gctobj = gct.GCT(infile)
    gctobj.read()
    
    data = gctobj.matrix[:, :].astype('float64')
    
    np.save(outfile, data)
    
        
if __name__ == '__main__':
    main()
```

**Comment by oena** [comment]
Hi @FarshidShekari, I'm not sure I totally follow your logic. gctx2gct is already included as a command-line method, so I'm not sure why you're writing your own. If you have cmapPy properly set up in your conda environment or installed, you can already run it as a command line script. 

That being said, if you'd like to convert a file in a Python session, it's a two-liner: you can just parse the file in and then write it to whichever (gct, gctx) format would be most convenient.

**Comment by oena** [comment]
Ah, ok. If you're not using the conda environment, you need to run it like
a python script: ie. python gctx2gct.py -filename my/file/path

**Comment by FarshidShekari** [comment]
I mentioned in above, I write my code in a file like below
```
import sys
from cmapPy.pandasGEXpress import gctx2gct


def main():
    gctx2gct.gctx2gct_main(sys.argv)


if __name__ == '__main__':
    main()
```
and saved in a file with name `ab.py`. When I want to run it with this command `python ab.py zzzz.gctx jjjj.gct` in cmd I get the mentioned error. How handle it?

**Comment by oena** [comment]
You can just import cmapPy.pandasGEXpress.parse and
cmapPy.pandasGEXpress.write_gct instead, and add two lines instead of the
one you currently have in your main method to (1) parse in the gctx and
then (2) write it out to gct.
