### ISSUE TITLE
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

### ISSUE THREAD

**Issue by FarshidShekari** [cmap/cmapPy#52]
When I want to read `gctx` file. Is fixable?

 ```
 File "C:/Users/Farshid/PycharmProjects/DGEP/gctx2npy.py", line 13, in main
    gctobj = parse.parse(GTEx_GCTX)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse.py", line 68, in parse
    make_multiindex=make_multiindex)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse_gctx.py", line 110, in parse
    data_df = parse_data_df(data_dset, sorted_ridx, sorted_cidx, row_meta, col_meta)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse_gctx.py", line 332, in parse_data_df
    data_array = np.empty(data_dset.shape, dtype=np.float32)
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.2\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 382, in _on_run
    r = self.sock.recv(1024)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by oena** [comment]
Hi @FarshidShekari, given your error message this seems like a connectivity or firewall issue, not an issue with cmapPy; if you [google your error message](https://www.google.com/search?q=A+connection+attempt+failed+because+the+connected+party+did+not+properly+respond+after+a+period+of+time%2C+or+established+connection+failed+because+connected+host+has+failed+to+respond&oq=A+connection+attempt+failed+because+the+connected+party+did+not+properly+respond+after+a+period+of+time%2C+or+established+connection+failed+because+connected+host+has+failed+to+respond&aqs=chrome..69i57j69i64l3.358j0j7&sourceid=chrome&ie=UTF-8), there seem to be a number of suggestions on how to approach this issue.

**Comment by FarshidShekari** [comment]
I set permission to `Pycharm` but it raises the error:
``ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
``

```
File "C:/Users/Farshid/PycharmProjects/DGEP/gctx2npy.py", line 13, in main
   gctobj = parse.parse(GTEx_GCTX)
 File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse.py", line 68, in parse
   make_multiindex=make_multiindex)
 File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse_gctx.py", line 110, in parse
   data_df = parse_data_df(data_dset, sorted_ridx, sorted_cidx, row_meta, col_meta)
 File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cmapPy\pandasGEXpress\parse_gctx.py", line 332, in parse_data_df
   data_array = np.empty(data_dset.shape, dtype=np.float32)
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
Traceback (most recent call last):
 File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.2\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 382, in _on_run
   r = self.sock.recv(1024)
```

**Comment by oena** [comment]
Hi Farshid, it looks like your file is too large to read into memory on whatever setup you're using. Probably a better approach would be to use hyperslab selection to only read in portions of the file; the [cmapPy tutorial](https://github.com/cmap/cmapPy/blob/master/tutorials/cmapPy_pandasGEXpress_tutorial.ipynb) has an example of how to do this.
