### ISSUE TITLE
Error during parsing

### ISSUE THREAD

**Issue by LeskosekRok** [cmap/cmapPy#67]
I'm trying to read a gctx file downloaded from https://clue.io/data. This is my code:

`from cmapPy.pandasGEXpress.parse_gct import parse`
`from cmapPy.pandasGEXpress.write_gct import write`
`parse("C:/Users/User/Desktop/gctx/testdatan1000978.gctx")`

This is the error:
`(base) C:\Users\User\Desktop\hello>D:/anaconda/python.exe c:/Users/User/Desktop/gctx/readgcxtx.py`
`The given path to the gct file cannot be found. gct_path: C:/Users/User/Desktop/gctx/testdatan1000978.gctx`
`Traceback (most recent call last):`
  `File "c:/Users/User/Desktop/gctx/readgcxtx.py", line 3, in <module>`
    `parse("C:/Users/User/Desktop/gctx/testdatan1000978.gctx")`
 ` File "D:\anaconda\lib\site-packages\cmapPy\pandasGEXpress\parse_gct.py", line 131, in parse`
    `raise Exception(err_msg.format(file_path))`
`Exception: The given path to the gct file cannot be found. gct_path: C:/Users/Rok/Desktop/gctx/testdatan1000978.gctx`

**Comment by tnat1031** [comment]
Hi @LeskosekRok, I am wondering if this might be an issue with the file path on windows. As a test, could you try changing directories into the folder with the gctx file, and then trying to read it?

in that case, the call would just be

```
parse("testdatan1000978.gctx")
```

**Comment by LeskosekRok** [comment]
Thanks for the swift reply. I'm not sure what you mean. All the files are in the same directory and if I execute the following:

`from` cmapPy.pandasGEXpress.parse_gct import parse`
`from cmapPy.pandasGEXpress.write_gct import write`
`parse(r"testdata_n1000978.gctx")`

I get:

`(base) C:\Users\Rok\Desktop\hello>D:/anaconda/python.exe c:/Users/Rok/Desktop/gctx/readgcxtx.py`
T`he given path to the gct file cannot be found. gct_path: testdatan1000978.gctx`
`Traceback (most recent call last):`
  `File "c:/Users/Rok/Desktop/gctx/readgcxtx.py", line 3, in <module>`
    `parse("testdatan1000978.gctx")`
  `File "D:\anaconda\lib\site-packages\cmapPy\pandasGEXpress\parse_gct.py", line 131, in parse`
    `raise Exception(err_msg.format(file_path))`
`Exception: The given path to the gct file cannot be found. gct_path: testdatan1000978.gctx`

**Comment by LeskosekRok** [comment]
OK, so gct files get parsed but not gctx. So the problem probably isn't on the part of the software..
