### ISSUE TITLE
Error in parsing

### ISSUE THREAD

**Issue by DeepColin** [cmap/cmapPy#70]

**Comment by DeepColin** [comment]
when I tried to parse the cmap2020, there were errors as follow:

Traceback (most recent call last):
  File "get_gct.py", line 17, in <module>
    get_gct()
  File "get_gct.py", line 13, in get_gct
    goo = cp_p.parse('level5_beta_trt_cp_n720216x12328.gctx',cid=brd_cid)
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/cmapPy/pandasGEXpress/parse.py", line 68, in parse
    make_multiindex=make_multiindex)
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/cmapPy/pandasGEXpress/parse_gctx.py", line 110, in parse
    data_df = parse_data_df(data_dset, sorted_ridx, sorted_cidx, row_meta, col_meta)
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/cmapPy/pandasGEXpress/parse_gctx.py", line 338, in parse_data_df
    first_subset = data_dset[cidx, :].astype(np.float32)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490027549092/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490027549092/work/h5py/_objects.c:2804)
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 474, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/wuxiaolong/.conda/envs/my_cmapPy_env/lib/python2.7/site-packages/h5py/_hl/selections.py", line 392, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment
